---
components:
  - name: ina226
    description: Driver for INA226 bidirectional current / power monitor
    group: current
    groups: []
    code_owners: menghang
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: menghang
        year: 2022
